/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyERC1155__factory } from "./MyERC1155__factory";
export { MyToken__factory } from "./MyToken__factory";
